# -*- coding: utf-8 -*-
from .constantModel import CcppConstant


# CCPP 汽轮机部分
CcppTurbine_data = [
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_turbine_efficiency",
        "name": "汽轮机内效率",
        "symbol": "ηTi",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.78",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_mechanical_efficiency",
        "name": "机械效率",
        "symbol": "ηm",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.95",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_generator_efficiency",
        "name": "发电机效率",
        "symbol": "ηg",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.973",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_flow",
        "name": "进气量",
        "symbol": "G1",
        "unit": "t/h",
        "calculate": "热源产生主蒸汽总流量",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_entropy",
        "name": "熵",
        "symbol": "",
        "unit": "kJ/(kg·℃)",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_enthalpy",
        "name": "焓",
        "symbol": "Izo",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_point_pressure",
        "name": "压力",
        "symbol": "P2'",
        "unit": "Mpa",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "0.2",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_point_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "120.21",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_point_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "1.6",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_point_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_point_flow",
        "name": "抽气量",
        "symbol": "G2",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_after_steam",
        "name": "蒸汽量",
        "symbol": "G",
        "unit": "t/h",
        "calculate": "G1+G2",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_after_pressure",
        "name": "压力",
        "symbol": "P2'",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_after_enthalpy",
        "name": "焓",
        "symbol": "Ih",
        "unit": "kJ/kg",
        "calculate": "（（G1-G3）*Izob+G2*Izo'）/G",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_exhaust_after_entropy",
        "name": "熵",
        "symbol": "Sh",
        "unit": "kJ/(kg·℃)",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_exhaust_pressure",
        "name": "压力",
        "symbol": "P3",
        "unit": "Mpa",
        "calculate": "湿冷：0.005～0.007空冷0.015",
        "remark": "",
        "defaultvalue": "0.009",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_exhaust_enthalpy",
        "name": "焓",
        "symbol": "Ipo",
        "unit": "kJ/kg",
        "calculate": "汽轮机绝热等熵做功排汽焓值，查表",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },

    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_backpressure_pressure",
        "name": "压力",
        "symbol": "P3",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.5",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_backpressure_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_backpressure_enthalpy",
        "name": "焓",
        "symbol": "Ipo",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_backpressure_flow",
        "name": "流量",
        "symbol": "G3",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_gross_generation",
        "name": "总发电量",
        "symbol": "P",
        "unit": "kw",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_hot_data",
        "name": "回热抽汽经验数据",
        "symbol": "",
        "unit": "--",
        "calculate": "经验值：有高加0.85；无高加0.9；无低价0.95",
        "remark": "",
        "defaultvalue": "0.95",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_extraction",
        "name": "去除抽汽后",
        "symbol": "P",
        "unit": "MW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_extraction_select",
        "name": "选定",
        "symbol": "P",
        "unit": "MW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_water_loss",
        "name": "全厂汽水损失",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.03",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_throttle_flow",
        "name": "进汽量",
        "symbol": "",
        "unit": "t/h",
        "calculate": "选定",
        "remark": "",
        "defaultvalue": "300",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "h_assume",
        "name": "假设",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "h_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "高压设5-6回热，给水温度210-230；中温中压4-5及回热，给水温度150-170；1.3MPa低压2级回热，给水温度104；2.4MPa低压3-4级回热，给水温度150；根据情况选择加热器形式：汇集式或者疏水放流式加热器，汇集式带疏水泵将疏水打至给水；假定换热效率0.98。",
        "defaultvalue": "50",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "h_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "h_enthalpy",
        "name": "焓值",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "h_amount",
        "name": "量",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },


    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "215",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh1_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh2_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "hh3_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh1_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh3_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_top_difference",
        "name": "上端差",
        "symbol": "φ",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "2.8",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_saturated_water_temperature",
        "name": "饱和水温度--加热器疏水温度",
        "symbol": "te‘",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_saturated_water_enthalpy",
        "name": "饱和水焓",
        "symbol": "he’",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "lh2_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "d_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_water_temperature",
        "name": "给水出水温度",
        "symbol": "tw2",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_water_enthalpy",
        "name": "给水出口焓",
        "symbol": "hw2",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_work_pressure",
        "name": "工作压力",
        "symbol": "pe‘",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_pressure_loss",
        "name": "抽汽管压损",
        "symbol": "ΔPe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.08",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_extraction_pressure",
        "name": "抽汽压力",
        "symbol": "Pe",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_extraction_enthalpy",
        "name": "抽汽焓",
        "symbol": "he",
        "unit": "kj/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "c_extraction_amount",
        "name": "抽汽量",
        "symbol": "Δde‘",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_turbine_efficiency",
        "name": "汽轮机内效率",
        "symbol": "ηTi",
        "unit": "--",
        "calculate": "",
        "remark": "（1）注意补汽压力所对应的的补汽点位置；（2）注意无高加时，高加抽气压力需手动修改",
        "defaultvalue": "0.82",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_mechanical_efficiency",
        "name": "机械效率",
        "symbol": "ηm",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.95",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_generator_efficiency",
        "name": "发电机效率",
        "symbol": "ηg",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "0.97",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_flow",
        "name": "流量",
        "symbol": "G1",
        "unit": "t/h",
        "calculate": "热源产生主蒸汽总流量",
        "remark": "",
        "defaultvalue": "300",
        "minmodelid": "",
        "controltype": "",
        "permission": "true"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_entropy",
        "name": "熵",
        "symbol": "",
        "unit": "kJ/(kg·℃)",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_enthalpy",
        "name": "焓",
        "symbol": "Izo",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high1_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high1_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high1_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high1_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high1_flow",
        "name": "流量",
        "symbol": "GH1",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_hh1_power",
        "name": "主汽至HH1功率",
        "symbol": "P2",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high2_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high2_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high2_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high2_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_high2_flow",
        "name": "流量",
        "symbol": "GH2",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_hh1_hh2_power",
        "name": "HH1至HH2功率",
        "symbol": "P3",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_flow",
        "name": "流量",
        "symbol": "GD",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_hh2_deoxidize_power",
        "name": "HH2至D功率",
        "symbol": "P4",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_point_pressure",
        "name": "压力",
        "symbol": "P2'",
        "unit": "Mpa",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_point_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "设计参数",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_point_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_point_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "实际焓值",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_point_flow",
        "name": "流量",
        "symbol": "G2",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_deoxidize_exhaust_power",
        "name": "D至抽汽功率",
        "symbol": "P1",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low1_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low1_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low1_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low1_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low1_flow",
        "name": "流量",
        "symbol": "GL2",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_exhaust_lh1_power",
        "name": "抽汽至LH1功率",
        "symbol": "P5",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low2_pressure",
        "name": "压力",
        "symbol": "",
        "unit": "Mpa",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low2_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low2_temperature",
        "name": "温度",
        "symbol": "",
        "unit": "℃",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low2_enthalpy",
        "name": "焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_low2_flow",
        "name": "流量",
        "symbol": "GL2",
        "unit": "t/h",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_lh1_lh2_power",
        "name": "LH1至LH2功率",
        "symbol": "P6",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_pressure",
        "name": "压力",
        "symbol": "P3",
        "unit": "Mpa",
        "calculate": "湿冷：0.005～0.007空冷0.015",
        "remark": "",
        "defaultvalue": "0.005",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_entropy",
        "name": "熵",
        "symbol": "S'",
        "unit": "kJ/(kg·℃)",
        "calculate": "主蒸汽绝热等熵",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_enthalpy",
        "name": "焓",
        "symbol": "Ipo",
        "unit": "kJ/kg",
        "calculate": "汽轮机绝热等熵做功排汽焓值，查表",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_enthalpy_actual",
        "name": "实际焓",
        "symbol": "Ipo‘",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_enthalpy_steam",
        "name": "饱和蒸汽焓",
        "symbol": "Ipog",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_enthalpy_water",
        "name": "饱和水焓",
        "symbol": "Ipos",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_dry",
        "name": "干度",
        "symbol": "x",
        "unit": "--",
        "calculate": "(Ipo'-Ipos）/（Ipog-Ipos）小型汽轮机排汽湿度控制在10~12%以内",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_steam_exhaust_flow",
        "name": "流量",
        "symbol": "GL2",
        "unit": "t/h",
        "calculate": "压力提高，排汽干度降低；",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_lh2_steam_power",
        "name": "LH2至乏汽功率",
        "symbol": "P7",
        "unit": "KW",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_total_power",
        "name": "总功率",
        "symbol": "",
        "unit": "--",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "i_calculation_error",
        "name": "计算误差",
        "symbol": "",
        "unit": "%",
        "calculate": "±3%以内",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    },
    {
        "module_name": "ccpp_Turbine",
        "name_eng": "e_steam_plus_enthalpy",
        "name": "补汽焓",
        "symbol": "Izob",
        "unit": "kJ/kg",
        "calculate": "",
        "remark": "",
        "defaultvalue": "",
        "minmodelid": "",
        "controltype": "",
        "permission": "false"
    }
]


class InitCcppTurbine():
    # 初始化数据
    @staticmethod
    def init_data():
        data = [
            CcppTurbine_data
        ]
        for index in range(len(data)):
            InitCcppTurbine.insert_constant(data[index])

    # 表中插入常量数据
    @staticmethod
    def insert_constant(data):
        module_name = data[0]["module_name"]
        for index in range(len(data)):
            name_eng = data[index]["name_eng"]
            name = data[index]["name"]
            symbol = data[index]["symbol"]
            unit = data[index]["unit"]
            calculate = data[index]["calculate"]
            remark = data[index]["remark"]
            defaultvalue = data[index]["defaultvalue"]
            minmodelid = data[index]["minmodelid"]
            controltype = data[index]["controltype"]
            permission = data[index]["permission"]
            ccppConstant = CcppConstant.create_ccppConstant(
                module_name, name_eng, name, symbol, unit, calculate, remark,
                defaultvalue, minmodelid, controltype, permission)
            CcppConstant.insert_ccppConstant(ccppConstant)
